### PR TITLE
Add accessibility to carousels

### PR DESCRIPTION
**Pull request by madison-boman**
Hides the carousels and, provides a list of items only to screenreaders.

### CODE REVIEW

**Review by iafb — COMMENTED** [review]
Do you think it'd be beneficial to include a description of what this section is for the screen reader? I'm worried without context it could just be seen like a random jumble of words and cause confusion, especially if the carousel lacks a heading.

**Comment by madison-boman** [comment]
> Do you think it'd be beneficial to include a description of what this section is for the screen reader? I'm worried without context it could just be seen like a random jumble of words and cause confusion, especially if the carousel lacks a heading.

Not sure if you saw but, `@Model.Carousel.Heading` currently describes to the user using an h2. The unordered list is hidden visually so, when the screenreader approaches, if will read "unordered list of # items. List item: <item's title>" for all the items. The actual carousel itself is hidden from the screen reader so, they wont deal with that audio mess.

**Comment by iafb** [comment]
> 
> 
> > Do you think it'd be beneficial to include a description of what this section is for the screen reader? I'm worried without context it could just be seen like a random jumble of words and cause confusion, especially if the carousel lacks a heading.
> 
> Not sure if you saw but, `@Model.Carousel.Heading` currently describes to the user using an h2. The unordered list is hidden visually so, when the screenreader approaches, it will read "unordered list of # items. List item: <item's title>" for all the items. The actual carousel itself is hidden from the screen reader so, they wont deal with that audio mess.

Ah okay that makes a lot more sense, I haven't looked into how a screenreader would read off the tags and was worried it'd just read off the text without the context that it's in a list. Sounds good how it is!

**Review by iafb — APPROVED** [review]

**Comment by k7hpn** [comment]
@madison-boman should the `@item.Title` elements be clickable links like they are in the carousel? Or did we not do that because they are JS modals and that would be weird?

**Comment by madison-boman** [comment]
> @madison-boman should the `@item.Title` elements be clickable links like they are in the carousel? Or did we not do that because they are JS modals and that would be weird?

@k7hpn I didn't make them links because, the modal only displays the book cover and the Title. I thought it'd just be easier if it was just presenting the title

**Pull request merged**
