### PR TITLE
Feature for allowing users to specify a custom goal.

### PR DESCRIPTION
**Pull request by justinmeiners**
The following changes are all system optional and disabled by default. 
- Added DailyGoal field to registration process.
- Added Goal percentage field to awards, which allows awards to be triggered when a patron completes a given portion of their goal.
- Changed award query to check daily goal.
- Added goal progress bar to profile. (Only displays when enabled in registration settings)

Let me know if there is anything you would like me to modify.

Thanks!

### CODE REVIEW

**Comment by haraldnagel** [comment]
@justinmeiners - I have a couple questions on this:

1. I signed up with the default program which is 366 days in duration. I set my goal to 20 minutes a day and logged 170 points (at the default setting of 1 point-per-minute). The daily goal graph says I'm at 46% but my math says I'm at 170 / (366 * 20) which should be ~2.3%. Is my math wrong? Am I missing part of how this works (entirely possible)?

2. It looks like in the two `app_Award_GetPatronQualifyingAwards` sprocs you are doing math comparing `patron.points` and `patron.DailyGoal` - this works if the points-per-minute configuration is set 1:1. If the math is set differently then this might not work (e.g. if 1 minute counted for 10 points - or 10 minutes counted for 1 point). It may be easier just to do the math when people sign up and enter their goal (i.e. when the user enters their goal, look up the corresponding `ProgramGamePointConversion` value and do the math) and store the correct point goal rather than minute goal in `DailyGoal`. I'm not sure if you accounted for this somewhere and I'm missing it.

**Comment by justinmeiners** [comment]
Thanks for the feedback. I also realized one other issue. When they pass their goal, the progress bar will probably extend past the bounds so I need to limit that.

1. I will verify that the math did not get mixed up. In my testing it seemed to behave appropriately, and your math is correct so I will double check that.

2. I was not award of the ProgramGamePointConversion. Thank you for pointing it out. I thought about taking the approach of storing a "total goal" each time the daily goal is modified. My only concern was that I would have to make sure it was adjusted for each patron when the dates of the program were adjusted. Similarly storing a value dependent on the conversion factor would have to stay in sync with that. Do you think this would be a good route to go?

**Comment by haraldnagel** [comment]
For your point 2 - We can always put in the documentation that altering the dates of the program or the point conversion levels after the program starts will lead to unexpected behavior with the custom goal feature. It might be easier to resolve this specific problem with user instruction rather than code.

**Comment by justinmeiners** [comment]
Ill think about it. I didn't realize "books" and "pages" were alternative forms of entering data in the reading log. I may try to make the goal feature work with each of these.

**Comment by justinmeiners** [comment]
After playing with this a little bit I think I will take the approach of caching a "TotalGoal" which includes both the ProgramGamePointConversion and the program length. This will simplify those queries I modified and make it easier to be compatible with pages, or minutes as the goal.

**Comment by haraldnagel** [comment]
Sounds good!

**Comment by justinmeiners** [comment]
I have now pushed the major changes. I will be running additional tests, but it should be about ready. It now uses a "GoalCache" which is recalculated whenever the user changes their goal or submit reading. This accommodates changes to the duration of the program as well as takes into account ProgramGamePointConversion. The only constraints now are:

1) Programs using "books" instead of "pages" or "minutes" cannot use the goal feature. 
2) Swapping from "pages" to "minutes" during the program works fine technically, but has undefined results as users goal definitions have now changed underneath them.

**Pull request merged**
